export const APPOINTMENT_TEST_WORKFLOW_STATUS = {
  INITIATED: 'INITIATED',
  ON_HOLD: 'ON_HOLD',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
} as const;

export const APPOINTMENT_TEST_PAYMENT_STATUS = {
  PENDING: 'pending',
  PAID: 'paid',
} as const;

export const APPOINTMENT_TEST_LEGACY_PAYMENT_STATUS = {
  PENDING: 'pending',
  PAID: 'paid',
  FAILED: 'failed',
} as const;

export const APPOINTMENT_TEST_SAMPLE_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  SAMPLE_COLLECTION_PENDING: 'SAMPLE_COLLECTION_PENDING',
  SAMPLE_COLLECTED: 'SAMPLE_COLLECTED',
  SAMPLE_RECEIVED_AT_LAB: 'SAMPLE_RECEIVED_AT_LAB',
  EXPECTED_REPORT_READY_AT_SET: 'EXPECTED_REPORT_READY_AT_SET',
  SAMPLE_PROCESSING: 'SAMPLE_PROCESSING',
  TESTING_IN_PROGRESS: 'TESTING_IN_PROGRESS',
  QUALITY_CHECK: 'QUALITY_CHECK',
  COMPLETED: 'COMPLETED',
} as const;

export const APPOINTMENT_TEST_TRACKING_EVENT = {
  INITIATED: 'INITIATED',
  ON_HOLD: 'ON_HOLD',
  REJECTED: 'REJECTED',
  PAYMENT_MARKED_PAID: 'PAYMENT_MARKED_PAID',
  SAMPLE_COLLECTION_PENDING: 'SAMPLE_COLLECTION_PENDING',
  SAMPLE_COLLECTED: 'SAMPLE_COLLECTED',
  SAMPLE_RECEIVED_AT_LAB: 'SAMPLE_RECEIVED_AT_LAB',
  EXPECTED_REPORT_READY_AT_SET: 'EXPECTED_REPORT_READY_AT_SET',
  SAMPLE_PROCESSING: 'SAMPLE_PROCESSING',
  TESTING_IN_PROGRESS: 'TESTING_IN_PROGRESS',
  QUALITY_CHECK_DONE: 'QUALITY_CHECK_DONE',
  COMPLETED: 'COMPLETED',
} as const;

export const APPOINTMENT_TEST_SAMPLE_ACTION = {
  MARK_SAMPLE_COLLECTED: 'MARK_SAMPLE_COLLECTED',
  MARK_SAMPLE_RECEIVED_AT_LAB: 'MARK_SAMPLE_RECEIVED_AT_LAB',
  START_SAMPLE_PROCESSING: 'START_SAMPLE_PROCESSING',
  START_TESTING: 'START_TESTING',
  MARK_QUALITY_CHECK_DONE: 'MARK_QUALITY_CHECK_DONE',
  MARK_COMPLETED: 'MARK_COMPLETED',
} as const;

export const APPOINTMENT_TEST_STEP_STATUS = {
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
  LOCKED: 'LOCKED',
} as const;

export type AppointmentTestWorkflowStatus =
  (typeof APPOINTMENT_TEST_WORKFLOW_STATUS)[keyof typeof APPOINTMENT_TEST_WORKFLOW_STATUS];

export type AppointmentTestPaymentStatus =
  (typeof APPOINTMENT_TEST_PAYMENT_STATUS)[keyof typeof APPOINTMENT_TEST_PAYMENT_STATUS];

export type AppointmentTestSampleStatus =
  (typeof APPOINTMENT_TEST_SAMPLE_STATUS)[keyof typeof APPOINTMENT_TEST_SAMPLE_STATUS];

export type AppointmentTestSampleAction =
  (typeof APPOINTMENT_TEST_SAMPLE_ACTION)[keyof typeof APPOINTMENT_TEST_SAMPLE_ACTION];

export type AppointmentTestTrackingEvent =
  (typeof APPOINTMENT_TEST_TRACKING_EVENT)[keyof typeof APPOINTMENT_TEST_TRACKING_EVENT];
