export const DEFAULT_CLINIC_POLICY = {
  allowPatientCancel: true,
  allowDoctorCancel: true,
  allowReceptionistCancel: true,
  allowClinicAdminCancel: true,
  windowOnlineHours: 24,
  windowOfflineHours: 12,
  dailyLimitPerPatient: 3,
  weeklyLimitPerPatient: 10,
  monthlyLimitPerPatient: 30,
  cooldownSecondsBetweenCancellations: 1800,
  reasonMandatory: true,
  allowAdditionalComments: true,
  minCommentLength: 10,
  maxCommentLength: 500,
  allowReschedule: true,
  maxReschedules: 3,
  rescheduleWindowHours: 24,
  preservePaymentOnReschedule: true,
};
