export const SPECIALITY_SYMPTOMS: Record<string, string[]> = {
  "Andrologist": [
    "Erectile dysfunction",
    "Low libido",
    "Male infertility",
    "Testicular pain",
    "Prostate issues",
    "Premature ejaculation",
    "Scrotal swelling",
    "Hair loss (male pattern)",
    "Fatigue/Low testosterone",
    "Blood in semen"
  ],
  "Bariatric Surgeon": [
    "Severe obesity",
    "Inability to lose weight",
    "Sleep apnea due to weight",
    "Joint pain from excess weight",
    "Uncontrolled type 2 diabetes",
    "Hypertension associated with obesity",
    "Breathlessness on mild exertion",
    "Metabolic syndrome",
    "Acid reflux (GERD)",
    "Interest in weight loss surgery"
  ],
  "Cardiac Electrophysiologist": [
    "Heart palpitations",
    "Racing heart beat (tachycardia)",
    "Irregular pulse",
    "Fainting episodes (syncope)",
    "Dizziness or lightheadedness",
    "Shortness of breath",
    "Chest fluttering",
    "Slow heart rate (bradycardia)",
    "Fatigue during activity",
    "History of atrial fibrillation (AFib)"
  ],
  "Cardiologist": [
    "Chest pain or discomfort",
    "Shortness of breath (dyspnea)",
    "High blood pressure",
    "Swelling in legs or ankles (edema)",
    "Rapid or pounding heartbeat",
    "Dizziness/Lightheadedness",
    "Fatigue with minimal effort",
    "Pain radiating to left arm/jaw",
    "History of heart attack",
    "High cholesterol"
  ],
  "Cardiothoracic Surgeon": [
    "Severe chest pain",
    "Shortness of breath (severe)",
    "Heart valve problems",
    "Blocked coronary arteries",
    "Congenital heart defects",
    "Aneurysm symptoms",
    "Difficulty swallowing (dysphagia)",
    "Chronic cough with blood",
    "Persistent chest fluid (pleural effusion)",
    "History of bypass surgery recommendation"
  ],
  "Chest Specialist": [
    "Chronic cough",
    "Wheezing",
    "Shortness of breath",
    "Chest tightness",
    "Coughing up blood (hemoptysis)",
    "Snoring and sleep apnea",
    "Persistent phlegm",
    "Rapid breathing",
    "Pain when breathing deeply",
    "Exposure to toxic fumes/dust"
  ],
  "Colorectal Surgeon": [
    "Rectal bleeding",
    "Chronic constipation",
    "Chronic diarrhea",
    "Anal itching or pain",
    "Incontinence",
    "Blood in stool",
    "Hemorrhoids (piles)",
    "Abdominal pain or cramping",
    "Unexplained weight loss",
    "Anal fistula/fissure"
  ],
  "Cosmetologist": [
    "Acne scars",
    "Skin aging/Wrinkles",
    "Pigmentation/Dark spots",
    "Hair thinning/Loss",
    "Unwanted facial/body hair",
    "Sagging skin",
    "Uneven skin tone",
    "Dark circles",
    "Stretch marks",
    "Lip thinning/dryness"
  ],
  "Counsellor": [
    "Relationship conflict",
    "Anxiety/Worry",
    "Grief/Loss of a loved one",
    "Low self-esteem",
    "Stress management difficulties",
    "Life transitions",
    "Anger management issues",
    "Work-related burnout",
    "Mild depressive symptoms",
    "Coping with chronic illness"
  ],
  "Dentist": [
    "Toothache",
    "Bleeding gums",
    "Bad breath (halitosis)",
    "Tooth sensitivity (hot/cold)",
    "Loose teeth",
    "Cavities/Tooth decay",
    "Jaw pain (TMJ)",
    "Stained or discolored teeth",
    "Mouth sores",
    "Broken/Chipped tooth"
  ],
  "Dermatologist": [
    "Persistent acne",
    "Dry, itchy skin (eczema)",
    "Red, scaly patches (psoriasis)",
    "Suspicious moles or spots",
    "Rashes/Hives",
    "Hair loss or thinning",
    "Nail fungal infection",
    "Sunburn or skin damage",
    "Excessive sweating (hyperhidrosis)",
    "Warts/Skin tags"
  ],
  "Diabetologist": [
    "Frequent urination (polyuria)",
    "Excessive thirst (polydipsia)",
    "Extreme hunger",
    "Unexplained weight loss",
    "Tingling/Numbness in hands or feet",
    "Blurry vision",
    "Slow-healing cuts or sores",
    "Chronic fatigue",
    "Frequent skin or yeast infections",
    "High blood sugar readings"
  ],
  "Emergency Medicine Specialist": [
    "Sudden severe chest pain",
    "Difficulty breathing",
    "Sudden weakness or numbness",
    "Severe abdominal pain",
    "High fever with stiff neck",
    "Major physical trauma/Accidents",
    "Deep cuts or severe burns",
    "Uncontrollable bleeding",
    "Confusion or altered mental state",
    "Poison ingestion or overdose"
  ],
  "Endocrinologist": [
    "Sudden weight gain or loss",
    "Chronic fatigue/Weakness",
    "Temperature intolerance (hot/cold)",
    "Excessive hair growth (hirsutism)",
    "Irregular menstrual cycles",
    "Bone loss or frequent fractures",
    "Constant thirst and urination",
    "Growth abnormalities",
    "Mood swings and anxiety",
    "Swelling in the neck (goiter)"
  ],
  "Endodontist": [
    "Severe tooth pain when chewing",
    "Prolonged sensitivity to heat or cold",
    "Discoloration of a single tooth",
    "Swelling in gums near a painful tooth",
    "Tenderness in gums",
    "Recurring pimple on the gums",
    "Pain radiating to jaw or ear",
    "Cracked tooth extending to root",
    "Injury to a tooth causing nerve pain",
    "Internal tooth resorption"
  ],
  "ENT Specialist": [
    "Earache or ear discharge",
    "Hearing loss",
    "Nasal congestion/Runny nose",
    "Sore throat",
    "Difficulty swallowing",
    "Hoarseness or voice changes",
    "Sinus pain/Pressure",
    "Ringing in ears (tinnitus)",
    "Snoring and sleep apnea",
    "Dizziness or vertigo"
  ],
  "ENT Surgeon": [
    "Chronic tonsillitis",
    "Deviated nasal septum",
    "Chronic sinusitis needing surgery",
    "Vocal cord nodules",
    "Neck lumps or masses",
    "Nasal polyps",
    "Chronic middle ear infection",
    "Head/neck cancer symptoms",
    "Severe snoring/apnea needing surgery",
    "Perforated eardrum"
  ],
  "Family Medicine": [
    "General body weakness",
    "Mild fever",
    "Common cold and cough",
    "General check-up",
    "Minor cuts and sprains",
    "High blood pressure management",
    "Annual health screening",
    "Flu-like symptoms",
    "Mild stomach ache",
    "Routine vaccinations"
  ],
  "Fertility Specialist": [
    "Inability to conceive after 1 year",
    "Irregular or absent periods",
    "Recurrent miscarriages",
    "Low sperm count or motility",
    "History of pelvic inflammatory disease",
    "Endometriosis-related fertility issues",
    "Advanced maternal age (over 35)",
    "History of chemotherapy/fertility preservation",
    "Blocked fallopian tubes",
    "Hormonal imbalances preventing pregnancy"
  ],
  "Gastroenterologist": [
    "Persistent acid reflux",
    "Chronic abdominal bloating/pain",
    "Severe heartburn",
    "Blood in vomit or stool",
    "Difficulty swallowing",
    "Unexplained weight loss",
    "Chronic constipation or diarrhea",
    "Yellowing of skin/eyes (jaundice)",
    "Persistent nausea/vomiting",
    "Loss of appetite"
  ],
  "General Physician": [
    "High grade fever",
    "Body aches and fatigue",
    "Persistent cough and cold",
    "Mild chest congestion",
    "Headache or migraine",
    "Stomach upset/Diarrhea",
    "Blood pressure check",
    "Sore throat",
    "Unexplained dizziness",
    "Joint pain"
  ],
  "General Practitioner": [
    "Routine prescription renewal",
    "Cold and flu symptoms",
    "Ear infections",
    "Minor skin rashes",
    "Urinary tract infection (UTI)",
    "Minor muscle strain",
    "Preventive health counseling",
    "Chronic disease follow-up",
    "Allergy symptoms",
    "Insect bites/stings"
  ],
  "General Surgeon": [
    "Painful hernia",
    "Gallbladder pain/Gallstones",
    "Appendicitis symptoms",
    "Painful hemorrhoids/piles",
    "Skin abscess or cyst",
    "Swollen lymph nodes",
    "Thyroid nodule",
    "Abdominal wall swelling",
    "Gastrointestinal bleeding",
    "Intestinal obstruction"
  ],
  "Geriatrician": [
    "Memory loss or confusion",
    "Frequent falls/Balance issues",
    "Multiple chronic conditions",
    "Mobility decline",
    "Polypharmacy (taking many medications)",
    "Frailty and weight loss",
    "Urinary incontinence in elderly",
    "Difficulty performing daily tasks",
    "Osteoporosis management",
    "Sleep disorders in elderly"
  ],
  "Gynecologist": [
    "Irregular menstrual periods",
    "Heavy menstrual bleeding (menorrhagia)",
    "Painful periods (dysmenorrhea)",
    "Unusual vaginal discharge/odor",
    "Pelvic pain",
    "Vaginal itching or burning",
    "Missed period/Pregnancy check",
    "Menopausal symptoms (hot flashes)",
    "Pain during intercourse",
    "Routine Pap smear"
  ],
  "Hematologist": [
    "Easy bruising or bleeding",
    "Chronic anemia (low iron/hemoglobin)",
    "Frequent nosebleeds",
    "Swollen lymph nodes (painless)",
    "Deep vein thrombosis (DVT)",
    "Unexplained fatigue and paleness",
    "Frequent infections",
    "Abnormal blood count reports",
    "Enlarged spleen",
    "Blood clotting disorders"
  ],
  "Hepatologist": [
    "Jaundice (yellow skin/eyes)",
    "Abdominal swelling (ascites)",
    "Dark urine",
    "Pain in the upper right abdomen",
    "Chronic fatigue",
    "Nausea and loss of appetite",
    "Swelling in legs and ankles",
    "Easy bruising",
    "History of hepatitis infection",
    "Confused state (hepatic encephalopathy)"
  ],
  "Immunologist": [
    "Frequent/recurrent infections",
    "Chronic allergies (food/seasonal)",
    "Severe asthma",
    "Autoimmune symptoms (joint pain, rash)",
    "Eczema/Atopic dermatitis",
    "Chronic hives (urticaria)",
    "Anaphylaxis episodes",
    "Sinusitis not responding to treatment",
    "Immunodeficiency evaluation",
    "Drug allergies"
  ],
  "Infectious Disease Specialist": [
    "Prolonged/unexplained fever",
    "Infection not responding to antibiotics",
    "HIV/AIDS management",
    "Tuberculosis symptoms (chronic cough, night sweats)",
    "Travel-related illness (malaria, dengue)",
    "Lyme disease symptoms",
    "Chronic bone/joint infection",
    "Parasitic infections",
    "Meningitis symptoms",
    "Hepatitis B or C management"
  ],
  "Intensivist": [
    "Multi-organ failure",
    "Severe respiratory distress",
    "Sepsis or septic shock",
    "Comatose state",
    "Severe trauma recovery",
    "Acute cardiac arrest",
    "Life-threatening electrolyte imbalance",
    "Post-major surgery monitoring",
    "Severe pneumonia needing ventilator",
    "Shock or severe low blood pressure"
  ],
  "Interventional Cardiologist": [
    "Heart attack (acute chest pain)",
    "Angina (chest tightness on effort)",
    "Shortness of breath",
    "Blocked arteries (stenosis)",
    "Dizziness or fainting",
    "Heart valve narrowing",
    "Peripheral artery disease (leg pain when walking)",
    "High blood pressure (resistant)",
    "History of abnormal stress test",
    "Heart failure symptoms"
  ],
  "Nephrologist": [
    "Foamy urine",
    "Swelling in hands, face, legs (edema)",
    "High blood pressure (difficult to control)",
    "Decreased urine output",
    "Blood in urine (hematuria)",
    "Metallic taste in mouth",
    "Chronic fatigue",
    "Muscle cramps",
    "Itchy skin and nausea",
    "Abnormal kidney function test (high creatinine)"
  ],
  "Neurologist": [
    "Frequent or severe headaches",
    "Numbness, tingling or weakness",
    "Dizziness or loss of balance",
    "Tremors or involuntary movements",
    "Memory loss or confusion",
    "Seizures or blackouts",
    "Double or blurred vision",
    "Difficulty walking",
    "Slurred speech",
    "Chronic muscle weakness"
  ],
  "Neurosurgeon": [
    "Severe chronic back/neck pain",
    "Radiating leg/arm pain (sciatica)",
    "Numbness/weakness in limbs",
    "Brain tumor symptoms (seizures, headaches)",
    "Head injury/Concussion",
    "Spine fracture or injury",
    "Herniated disc",
    "Hydrocephalus symptoms",
    "Carpal tunnel syndrome (severe)",
    "Difficulty walking/balance issues"
  ],
  "Obstetrician": [
    "Morning sickness/Severe vomiting",
    "Missed period/Positive pregnancy test",
    "Fetal movement monitoring",
    "Swelling during pregnancy",
    "Pregnancy-induced hypertension",
    "Prenatal check-up",
    "Abdominal cramps during pregnancy",
    "Mild vaginal bleeding during pregnancy",
    "Gestational diabetes screening",
    "Contractions/Labour pain"
  ],
  "Occupational Therapist": [
    "Difficulty writing or holding utensils",
    "Developmental delays in children",
    "Sensory integration issues",
    "Difficulty with daily activities after stroke",
    "Hand/wrist injury rehabilitation",
    "Fine motor skill impairment",
    "Post-injury coordination issues",
    "Work-related repetitive strain",
    "Cognitive changes affecting daily tasks",
    "Adapting to assistive devices"
  ],
  "Oncologist": [
    "Unexplained weight loss",
    "Persistent fatigue",
    "Unusual lump or thickening under skin",
    "Changes in skin/mole appearance",
    "Persistent cough or hoarseness",
    "Unexplained pain",
    "Night sweats",
    "Persistent fever of unknown origin",
    "Easy bruising or bleeding",
    "Abnormality in biopsy report"
  ],
  "Ophthalmologist": [
    "Blurry or double vision",
    "Dry, burning, or itchy eyes",
    "Pain in or around the eyes",
    "Sudden loss of vision",
    "Flashes of light or floaters",
    "Sensitivity to light (photophobia)",
    "Red or bloodshot eyes",
    "Excess tearing or discharge",
    "Difficulty seeing at night",
    "Halos around lights"
  ],
  "Optometrist": [
    "Nearsightedness/Farsightedness",
    "Frequent headaches from eye strain",
    "Double vision",
    "Dry eyes",
    "Squinting or straining to read",
    "Blurred computer screen vision",
    "Need for reading glasses",
    "Routine eye examination",
    "Eye fatigue",
    "Prescribed contact lens check"
  ],
  "Oral and Maxillofacial Surgeon": [
    "Impacted wisdom teeth pain",
    "Jaw misalignment (underbite/overbite)",
    "Facial trauma or jaw fracture",
    "TMJ (jaw joint) disorders",
    "Cleft lip or palate",
    "Mouth, jaw or neck cysts/tumors",
    "Difficult tooth extractions",
    "Sleep apnea requiring jaw surgery",
    "Inadequate bone for dental implants",
    "Oral biopsy needs"
  ],
  "Orthodontist": [
    "Crooked teeth",
    "Crowded teeth",
    "Gaps between teeth",
    "Overbite or underbite",
    "Crossbite or open bite",
    "Difficulty chewing or biting",
    "Jaw clicking or popping",
    "Mouth breathing",
    "Sucking thumb habits in children",
    "Misaligned jaw alignment"
  ],
  "Orthopedic Doctor": [
    "Joint pain (knee, hip, shoulder)",
    "Muscle strain or ligament sprain",
    "Back pain or neck stiffness",
    "Fractures or suspected broken bones",
    "Swelling/bruising around joint",
    "Limited range of motion",
    "Sports injuries",
    "Numbness/tingling in hands/feet",
    "Chronic bone pain",
    "Arthritis symptoms"
  ],
  "Orthopedic Surgeon": [
    "Severe joint degeneration (arthritis)",
    "Ligament tear (ACL, meniscus)",
    "Rotator cuff tear",
    "Complex bone fractures",
    "Joint deformity",
    "Chronic back pain needing surgery",
    "Failed conservative joint treatment",
    "Hip or knee replacement inquiry",
    "Bone tumors",
    "Carpal tunnel release need"
  ],
  "Pain Specialist": [
    "Chronic low back pain",
    "Persistent neck pain",
    "Neuropathic (nerve) pain",
    "Fibromyalgia symptoms",
    "Complex Regional Pain Syndrome",
    "Joint pain resistant to medicine",
    "Chronic headaches/migraines",
    "Cancer-related pain",
    "Post-surgical pain",
    "Sciatica/Radiating pain"
  ],
  "Pediatrician": [
    "High fever in child",
    "Persistent cough or wheezing",
    "Ear pain or pulling at ears",
    "Childhood skin rashes",
    "Poor feeding or vomiting",
    "Delayed growth milestones",
    "Colic in infants",
    "Sore throat and difficulty swallowing",
    "Childhood vaccinations",
    "Behavioral/developmental concerns"
  ],
  "Periodontist": [
    "Bleeding gums during brushing",
    "Receding gum line",
    "Loose teeth",
    "Swollen, red, or tender gums",
    "Persistent bad breath",
    "Pain when chewing",
    "Pus between teeth and gums",
    "Changes in bite fit",
    "Plaque and tartar buildup",
    "Sensitive exposed tooth roots"
  ],
  "Physiotherapist": [
    "Post-stroke rehabilitation",
    "Muscle stiffness/pain",
    "Recovery after orthopedic surgery",
    "Balance and gait problems",
    "Chronic back or neck pain",
    "Sports injury recovery",
    "Repetitive strain injury",
    "Joint stiffness",
    "Postural corrections",
    "Breathing exercises for respiratory health"
  ],
  "Plastic Surgeon": [
    "Reconstruction after cancer removal",
    "Scar revision or reduction",
    "Burn injury scars",
    "Congenital anomalies (cleft lip/palate)",
    "Excess skin after weight loss",
    "Breast asymmetry or hypertrophy",
    "Facial rejuvenation interest",
    "Rhinoplasty (nasal deformity/breathing issues)",
    "Drooping eyelids (blepharoplasty)",
    "Keloid or hypertrophic scars"
  ],
  "Psychiatrist": [
    "Severe anxiety or panic attacks",
    "Persistent low mood/Depression",
    "Mood changes (mania/depression)",
    "Auditory/Visual hallucinations",
    "Delusions or paranoia",
    "Thoughts of self-harm",
    "Severe insomnia/Sleep disturbances",
    "Obsessive thoughts/Compulsive behaviors",
    "Focus and attention issues (ADHD)",
    "Post-traumatic stress symptoms"
  ],
  "Psychologist": [
    "Relationship difficulties",
    "Managing chronic stress",
    "Grief or bereavement support",
    "Mild to moderate depression",
    "Phobias or excessive fears",
    "Parenting challenges",
    "Identity/Self-esteem issues",
    "Difficulty regulating emotions",
    "Coping with life adjustments",
    "Sleep hygiene issues"
  ],
  "Pulmonologist": [
    "Chronic shortness of breath",
    "Persistent dry or productive cough",
    "Wheezing or chest tightness",
    "Snoring or waking gasping for air",
    "Coughing up blood",
    "Chest pain when inhaling",
    "Occupational dust exposure",
    "Rapid or shallow breathing",
    "Sleep apnea symptoms",
    "Unexplained oxygen level drop"
  ],
  "Radiation Oncologist": [
    "Localized tumor needing radiation",
    "Pain from metastatic cancer",
    "Shrinking tumor before surgery",
    "Post-surgery cancer cell elimination",
    "Difficulty swallowing due to throat tumor",
    "Bone pain from cancer spread",
    "Brain metastasis symptoms",
    "Referral for radiation therapy",
    "Skin changes over tumor site",
    "Side effects of previous radiation"
  ],
  "Rheumatologist": [
    "Joint pain with morning stiffness",
    "Multiple painful swollen joints",
    "Muscle pain and fatigue",
    "Dry eyes and mouth (Sjogren's)",
    "Unexplained fevers and rash",
    "Pain in lower back and hips",
    "Fingers turning blue in cold (Raynaud's)",
    "Inflammatory arthritis symptoms",
    "Chronic widespread pain",
    "Abnormal autoimmune blood tests"
  ],
  "Speech Therapist": [
    "Stuttering or stammering",
    "Slurred or unclear speech",
    "Difficulty pronouncing words",
    "Language delay in children",
    "Hoarse or weak voice",
    "Difficulty understanding speech",
    "Swallowing problems (dysphagia)",
    "Speech loss after stroke (aphasia)",
    "Cognitive-communication deficits",
    "Voice pitch adjustments"
  ],
  "Spine Specialist": [
    "Chronic lower back pain",
    "Sharp pain radiating down leg",
    "Neck pain and stiffness",
    "Numbness or tingling in arms/legs",
    "Loss of balance when walking",
    "Difficulty standing straight",
    "Spine deformity (scoliosis)",
    "Sharp pain when bending",
    "Muscle spasms in back",
    "Weakness in foot/foot drop"
  ],
  "Sports Medicine Specialist": [
    "Joint sprain or ligament tear",
    "Muscle pull/strain",
    "Shin splints",
    "Tennis or golfer's elbow",
    "Concussion evaluation",
    "Exercise-induced asthma",
    "Overuse injuries",
    "Knee pain (runner's knee)",
    "Joint swelling after activity",
    "Performance nutrition counseling"
  ],
  "Thyroid Specialist": [
    "Rapid weight loss or gain",
    "Persistent fatigue or lethargy",
    "Heart palpitations or fast pulse",
    "Feeling excessively cold or hot",
    "Swelling in the front of neck",
    "Hair loss and dry skin",
    "Muscle weakness and tremors",
    "Irregular menstrual periods",
    "Constipation or frequent bowel movements",
    "Sleep issues and anxiety"
  ],
  "Trichologist": [
    "Excessive hair shedding",
    "Patchy hair loss (alopecia)",
    "Scalp itching or flaking (dandruff)",
    "Oily or greasy scalp",
    "Thinning hair or receding hairline",
    "Dry, brittle, or breaking hair",
    "Scalp redness or inflammation",
    "Psoriasis on scalp",
    "Folliculitis (painful hair follicles)",
    "Unexplained scalp pain"
  ],
  "Urologic Surgeon": [
    "Blood in urine (hematuria)",
    "Severe flank/kidney pain (stones)",
    "Prostate enlargement symptoms",
    "Difficulty urinating (hesitancy)",
    "Urinary incontinence (severe)",
    "Testicular tumor or lump",
    "Bladder control issues",
    "Recurrent urinary tract infections",
    "Elevated PSA test results",
    "Phimosis or circumcision needs"
  ],
  "Urologist": [
    "Painful urination (dysuria)",
    "Frequent urination at night (nocturia)",
    "Weak urine flow",
    "Urinary urgency",
    "Kidney stone pain (back/side pain)",
    "Inability to empty bladder",
    "Erectile dysfunction",
    "Male infertility issues",
    "Involuntary leakage of urine",
    "Pain in scrotum or testicles"
  ],
  "Vascular Specialist": [
    "Painful varicose veins",
    "Leg swelling and heaviness",
    "Cold feet or toes",
    "Leg cramps when walking (claudication)",
    "Non-healing wounds/ulcers on legs",
    "Numbness or tingling in legs",
    "Spider veins",
    "Darkening skin color on lower legs",
    "History of stroke or TIA",
    "Family history of aneurysm"
  ],
  "Vascular Surgeon": [
    "Severe leg pain on walking (severe PAD)",
    "Abdominal aortic aneurysm (AAA)",
    "Deep vein thrombosis (DVT)",
    "Carotid artery blockage (stroke risk)",
    "Diabetic foot ulcers",
    "Varicose veins requiring surgery",
    "Leg swelling/ venous insufficiency",
    "Dialysis access (fistula) creation",
    "Chronic limb-threatening ischemia",
    "Blood clots in arms or legs"
  ]
};
