export const DOCTOR_SPECIALITIES = [
  "Andrologist",
  "Bariatric Surgeon",
  "Cardiac Electrophysiologist",
  "Cardiologist",
  "Cardiothoracic Surgeon",
  "Chest Specialist",
  "Colorectal Surgeon",
  "Cosmetologist",
  "Counsellor",
  "Dentist",
  "Dermatologist",
  "Diabetologist",
  "Emergency Medicine Specialist",
  "Endocrinologist",
  "Endodontist",
  "ENT Specialist",
  "ENT Surgeon",
  "Family Medicine",
  "Fertility Specialist",
  "Gastroenterologist",
  "General Physician",
  "General Practitioner",
  "General Surgeon",
  "Geriatrician",
  "Gynecologist",
  "Hematologist",
  "Hepatologist",
  "Immunologist",
  "Infectious Disease Specialist",
  "Intensivist",
  "Interventional Cardiologist",
  "Nephrologist",
  "Neurologist",
  "Neurosurgeon",
  "Obstetrician",
  "Occupational Therapist",
  "Oncologist",
  "Ophthalmologist",
  "Optometrist",
  "Oral and Maxillofacial Surgeon",
  "Orthodontist",
  "Orthopedic Doctor",
  "Orthopedic Surgeon",
  "Pain Specialist",
  "Pediatrician",
  "Periodontist",
  "Physiotherapist",
  "Plastic Surgeon",
  "Psychiatrist",
  "Psychologist",
  "Pulmonologist",
  "Radiation Oncologist",
  "Rheumatologist",
  "Speech Therapist",
  "Spine Specialist",
  "Sports Medicine Specialist",
  "Thyroid Specialist",
  "Trichologist",
  "Urologic Surgeon",
  "Urologist",
  "Vascular Specialist",
  "Vascular Surgeon",
];