import dbManager from '../../../database/DatabaseManager.js';
import DiscoveryService from './DiscoveryService.js';
import logger from '../../../utils/logger.js';
import { EventLogRepository, type EventLogEntry } from '../infrastructure/repositories/EventLogRepository.js';
import NodeIdentity from './NodeIdentity.js';
import { EventProjector } from './EventProjector.js';
import axios from 'axios';

class SyncClient {
  private syncInterval: NodeJS.Timeout | null = null;
  private eventLogRepo = new EventLogRepository();
  private isSyncing = false;

  public start() {
    // Poll peers every 10 seconds
    this.syncInterval = setInterval(() => this.runSyncCycle(), 10000);
    logger.info('[SyncClient] Started P2P Sync Client loop.');
  }

  public stop() {
    if (this.syncInterval) {
      clearInterval(this.syncInterval);
      this.syncInterval = null;
    }
    logger.info('[SyncClient] Stopped P2P Sync Client loop.');
  }

  private async runSyncCycle() {
    if (this.isSyncing) return;
    this.isSyncing = true;

    try {
      const peers = DiscoveryService.getActivePeers();
      if (peers.length === 0) return;

      const localClock = NodeIdentity.getCurrentLamportClock();
      const localNodeId = NodeIdentity.getNodeId();

      for (const peer of peers) {
        try {
          // Fetch events that occurred after our current knowledge
          const url = `http://${peer.ip}:5002/p2p/events?since_clock=${localClock}&node_id=${localNodeId}`;
          const response = await axios.get(url, { timeout: 5000 });
          
          if (response.data && Array.isArray(response.data.events)) {
            const events: EventLogEntry[] = response.data.events;
            this.mergeEvents(events);
          }
        } catch (e: any) {
          logger.warn(`[SyncClient] Failed to pull from peer ${peer.nodeId} (${peer.ip}): ${e.message}`);
        }
      }
    } catch (err) {
       logger.error('[SyncClient] Unexpected error in sync cycle', err);
    } finally {
      this.isSyncing = false;
    }
  }

  private mergeEvents(events: EventLogEntry[]) {
    if (events.length === 0) return;
    
    let mergedCount = 0;
    
    try {
      const db = dbManager.getConnection();
      const transaction = db.transaction(() => {
        for (const event of events) {
          // Skip events originally generated by ourselves to prevent echo loops
          if (event.node_id === NodeIdentity.getNodeId()) continue;

          // Check if event already exists locally
          const existing = this.eventLogRepo.getEventById(db, event.id);
          
          if (existing) {
             // If we already have this exact event ID, we skip it or update status.
             // We use Lamport Clock to break ties if they were somehow conflicting on the same ID (unlikely for UUIDs).
             if (event.lamport_clock! > existing.lamport_clock! || 
                (event.lamport_clock === existing.lamport_clock && event.node_id! > existing.node_id!)) {
                this.eventLogRepo.upsertEvent(db, event);
             }
          } else {
             // It's a new event from a peer
             this.eventLogRepo.upsertEvent(db, event);
             mergedCount++;
             
             // Project this event onto the local SQLite read-models (patients, appointments tables)
             EventProjector.project(db, event);
          }
        }
      });
      
      transaction();
      
      if (mergedCount > 0) {
        logger.info(`[SyncClient] Successfully replicated ${mergedCount} new events from peers.`);
        // Notify the frontend via Socket.io
        import('./SyncServer.js').then((module) => {
          module.default.broadcastDbUpdated();
        });
      }
    } catch (e) {
      logger.error(`[SyncClient] Failed to merge events:`, e);
    }
  }
}

export default new SyncClient();
