export const doctorRutineDufet = {
  aivblity: [
    {
      dayOfWeek: 'Monday',
      startTime: '09:00 AM',
      endTime: '06:00 PM',
      isAvailable: true,
      notes: '',
      slotMinutes: 30,
      stepMinutes: 15,
      aivblityBreak: [
        {
          breakType: 'Lunch Break',
          startTime: '01:00 PM',
          endTime: '02:00 PM',
          status: true,
          notes: 'Lunch',
        },
      ],
    },
    {
      dayOfWeek: 'Tuesday',
      startTime: '09:00 AM',
      endTime: '06:00 PM',
      isAvailable: true,
      notes: '',
      slotMinutes: 30,
      stepMinutes: 15,
      aivblityBreak: [
        {
          breakType: 'Lunch Break',
          startTime: '01:00 PM',
          endTime: '02:00 PM',
          status: true,
          notes: 'Lunch',
        },
      ],
    },
    {
      dayOfWeek: 'Wednesday',
      startTime: '09:00 AM',
      endTime: '06:00 PM',
      isAvailable: true,
      notes: '',
      slotMinutes: 30,
      stepMinutes: 15,
      aivblityBreak: [
        {
          breakType: 'Lunch Break',
          startTime: '01:00 PM',
          endTime: '02:00 PM',
          status: true,
          notes: 'Lunch',
        },
      ],
    },
    {
      dayOfWeek: 'Thursday',
      startTime: '09:00 AM',
      endTime: '06:00 PM',
      isAvailable: true,
      notes: '',
      slotMinutes: 30,
      stepMinutes: 15,
      aivblityBreak: [
        {
          breakType: 'Lunch Break',
          startTime: '01:00 PM',
          endTime: '02:00 PM',
          status: true,
          notes: 'Lunch',
        },
      ],
    },
    {
      dayOfWeek: 'Friday',
      startTime: '09:00 AM',
      endTime: '06:00 PM',
      isAvailable: true,
      notes: '',
      slotMinutes: 30,
      stepMinutes: 15,
      aivblityBreak: [
        {
          breakType: 'Lunch Break',
          startTime: '01:00 PM',
          endTime: '02:00 PM',
          status: true,
          notes: 'Lunch',
        },
      ],
    },
    {
      dayOfWeek: 'Saturday',
      startTime: '09:00 AM',
      endTime: '06:00 PM',
      isAvailable: true,
      notes: '',
      slotMinutes: 30,
      stepMinutes: 15,
      aivblityBreak: [
        {
          breakType: 'Lunch Break',
          startTime: '01:00 PM',
          endTime: '02:00 PM',
          status: true,
          notes: 'Lunch',
        },
      ],
    },
    {
      dayOfWeek: 'Sunday',
      startTime: '09:00 AM',
      endTime: '06:00 PM',
      isAvailable: true,
      notes: '',
      slotMinutes: 30,
      stepMinutes: 15,
      aivblityBreak: [
        {
          breakType: 'Lunch Break',
          startTime: '01:00 PM',
          endTime: '02:00 PM',
          status: true,
          notes: 'Lunch',
        },
      ],
    },
  ],
};
