export const DOCTOR_SPECIALTY_CONFIG = {
  'General Physician': {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Sedentary lifestyle',
      'Poor sleep',
      'High caffeine intake',
      'Irregular meals',
    ],
    allergy_list: [
      'Dust',
      'Pollen',
      'Food allergy',
      'Drug allergy',
      'Cold weather',
      'Pet dander',
    ],
    diagnosis_list: [
      'Fever',
      'Common Cold',
      'Body Pain',
      'Viral Infection',
      'Gastritis',
      'Hypertension',
      'Diabetes',
      'Fatigue',
    ],
    surgery_suggested_list: [
      'Appendectomy',
      'Hernia repair',
      'Gallbladder removal',
      'Minor cyst removal',
    ],
    dietary_suggestions_list: [
      'Drink boiled water.',
      'Avoid oily and fried foods.',
      'Include more fruits and vegetables.',
      'Limit caffeine intake.',
      'Eat small, frequent meals.',
    ],
  },

  'General Practitioner': {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Sedentary lifestyle',
      'Poor sleep',
      'High caffeine intake',
      'Irregular meals',
    ],
    allergy_list: [
      'Dust',
      'Pollen',
      'Food allergy',
      'Drug allergy',
      'Cold weather',
      'Pet dander',
    ],
    diagnosis_list: [
      'Fever',
      'Common Cold',
      'Body Pain',
      'Viral Infection',
      'Gastritis',
      'Hypertension',
      'Diabetes',
      'Fatigue',
    ],
    surgery_suggested_list: [
      'Appendectomy',
      'Hernia repair',
      'Gallbladder removal',
      'Minor cyst removal',
    ],
    dietary_suggestions_list: [
      'Drink boiled water.',
      'Avoid oily and fried foods.',
      'Include more fruits and vegetables.',
      'Limit caffeine intake.',
      'Eat small, frequent meals.',
    ],
  },

  Pediatrician: {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Thumb sucking',
      'Poor eating habits',
      'Excess screen time',
      'Irregular sleep',
      'Bottle feeding dependency',
    ],
    allergy_list: ['Milk', 'Peanuts', 'Dust', 'Eggs', 'Soy', 'Pet dander'],
    diagnosis_list: [
      'Fever',
      'Cold',
      'Cough',
      'Viral Infection',
      'Diarrhea',
      'Malnutrition',
      'Allergy',
      'Asthma',
    ],
    surgery_suggested_list: [
      'Tonsillectomy',
      'Hernia repair',
      'Appendectomy',
      'Adenoidectomy',
    ],
    dietary_suggestions_list: [
      'Encourage homemade balanced meals.',
      'Limit sugary snacks and drinks.',
      'Include dairy for strong bones.',
      'Offer small, frequent meals.',
      'Ensure adequate hydration with water.',
    ],
  },

  Gynecologist: {
    header_order: [
      'Diagnosis',
      'Allergy',
      'Vitals',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Follow-Up (days)',
      'Visiting Days',
      'Habits',
      'Surgery Suggested',
    ],
    habit_list: [
      'Poor hygiene',
      'Stress',
      'Irregular sleep',
      'Sedentary lifestyle',
      'Smoking',
      'Tobacco',
    ],
    allergy_list: [
      'Dust',
      'Eggs',
      'Drug allergy',
      'Latex allergy',
      'Food allergy',
    ],
    diagnosis_list: [
      'PCOS',
      'Irregular periods',
      'Pregnancy care',
      'UTI',
      'Hormonal imbalance',
      'Infertility',
      'Menstrual pain',
    ],
    surgery_suggested_list: [
      'C-section',
      'Hysterectomy',
      'Ovarian cyst removal',
      'Dilation and curettage',
      'Fibroid removal',
    ],
    dietary_suggestions_list: [
      'Increase iron-rich foods like leafy greens.',
      'Stay hydrated with warm water.',
      'Reduce refined sugars and processed foods.',
      'Include calcium and vitamin D sources.',
      'Eat high-fiber foods for hormonal balance.',
    ],
  },

  Obstetrician: {
    header_order: [
      'Diagnosis',
      'Allergy',
      'Vitals',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Follow-Up (days)',
      'Visiting Days',
      'Habits',
      'Surgery Suggested',
    ],
    habit_list: [
      'Poor hygiene',
      'Stress',
      'Irregular sleep',
      'Sedentary lifestyle',
      'Smoking',
      'Tobacco',
    ],
    allergy_list: [
      'Dust',
      'Eggs',
      'Drug allergy',
      'Latex allergy',
      'Food allergy',
    ],
    diagnosis_list: [
      'PCOS',
      'Irregular periods',
      'Pregnancy care',
      'UTI',
      'Hormonal imbalance',
      'Infertility',
      'Menstrual pain',
    ],
    surgery_suggested_list: [
      'C-section',
      'Hysterectomy',
      'Ovarian cyst removal',
      'Dilation and curettage',
      'Fibroid removal',
    ],
    dietary_suggestions_list: [
      'Take prenatal vitamins regularly.',
      'Eat protein-rich foods for fetal growth.',
      'Stay hydrated with water and juices.',
      'Avoid raw or undercooked foods.',
      'Include folate-rich foods like lentils.',
    ],
  },

  Dermatologist: {
    header_order: [
      'Diagnosis',
      'Allergy',
      'Advice',
      'Habits',
      'Dietary Suggestions',
      'Pathology Test Name',
      'Follow-Up (days)',
      'Visiting Days',
      'Vitals',
      'Surgery Suggested',
    ],
    habit_list: [
      'Excess sun exposure',
      'Poor hygiene',
      'Use of harsh cosmetics',
      'Smoking',
      'Stress',
      'Frequent sweating',
    ],
    allergy_list: [
      'Cosmetics',
      'Dust',
      'Food allergy',
      'Pollen',
      'Chemical exposure',
    ],
    diagnosis_list: [
      'Acne',
      'Eczema',
      'Psoriasis',
      'Fungal infection',
      'Allergic dermatitis',
      'Hair fall',
      'Pigmentation',
    ],
    surgery_suggested_list: [
      'Skin biopsy',
      'Laser therapy',
      'Mole removal',
      'Scar revision',
    ],
    dietary_suggestions_list: [
      'Drink plenty of water for skin hydration.',
      'Avoid high-glycemic foods like sugar.',
      'Include omega-3 fatty acids from fish.',
      'Eat antioxidant-rich fruits and vegetables.',
      'Limit dairy if acne-prone.',
    ],
  },

  'Orthopedic Doctor': {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Pathology Test Name',
      'Surgery Suggested',
      'Advice',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Dietary Suggestions',
      'Allergy',
    ],
    habit_list: [
      'Poor posture',
      'Heavy lifting',
      'Lack of exercise',
      'Prolonged sitting',
      'Improper ergonomics',
    ],
    allergy_list: [
      'Medication allergy',
      'Metal allergy',
      'Painkiller allergy',
      'Latex allergy',
    ],
    diagnosis_list: [
      'Fracture',
      'Arthritis',
      'Back pain',
      'Joint pain',
      'Ligament injury',
      'Osteoporosis',
      'Slip disc',
    ],
    surgery_suggested_list: [
      'Knee replacement',
      'Hip replacement',
      'Fracture fixation',
      'Arthroscopy',
      'Spine surgery',
    ],
    dietary_suggestions_list: [
      'Increase calcium and vitamin D intake.',
      'Eat protein-rich foods for bone healing.',
      'Stay hydrated for joint health.',
      'Avoid inflammatory foods like sugar.',
      'Include collagen-boosting foods.',
    ],
  },

  'Orthopedic Surgeon': {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Pathology Test Name',
      'Surgery Suggested',
      'Advice',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Dietary Suggestions',
      'Allergy',
    ],
    habit_list: [
      'Poor posture',
      'Heavy lifting',
      'Lack of exercise',
      'Prolonged sitting',
      'Improper ergonomics',
    ],
    allergy_list: [
      'Medication allergy',
      'Metal allergy',
      'Painkiller allergy',
      'Latex allergy',
    ],
    diagnosis_list: [
      'Fracture',
      'Arthritis',
      'Back pain',
      'Joint pain',
      'Ligament injury',
      'Osteoporosis',
      'Slip disc',
    ],
    surgery_suggested_list: [
      'Knee replacement',
      'Hip replacement',
      'Fracture fixation',
      'Arthroscopy',
      'Spine surgery',
    ],
    dietary_suggestions_list: [
      'Increase calcium and vitamin D intake.',
      'Eat protein-rich foods for bone healing.',
      'Stay hydrated for joint health.',
      'Avoid inflammatory foods like sugar.',
      'Include collagen-boosting foods.',
    ],
  },

  'ENT Specialist': {
    header_order: [
      'Diagnosis',
      'Allergy',
      'Vitals',
      'Pathology Test Name',
      'Advice',
      'Follow-Up (days)',
      'Visiting Days',
      'Habits',
      'Dietary Suggestions',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Cold food intake',
      'Poor hygiene',
      'Allergen exposure',
      'Loud noise exposure',
    ],
    allergy_list: ['Dust', 'Pollen', 'Cold air', 'Food allergy', 'Smoke'],
    diagnosis_list: [
      'Sinusitis',
      'Tonsillitis',
      'Ear infection',
      'Hearing loss',
      'Nasal blockage',
      'Throat infection',
    ],
    surgery_suggested_list: [
      'Tonsillectomy',
      'Septoplasty',
      'Ear surgery',
      'Sinus surgery',
    ],
    dietary_suggestions_list: [
      'Drink warm fluids like herbal tea.',
      'Avoid cold and refrigerated foods.',
      'Include honey to soothe the throat.',
      'Eat soft foods during infections.',
      'Stay hydrated with boiled water.',
    ],
  },

  Cardiologist: {
    header_order: [
      'Vitals',
      'Diagnosis',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'High salt intake',
      'Sedentary lifestyle',
      'Stress',
      'High fat diet',
    ],
    allergy_list: [
      'Drug allergy',
      'Contrast dye allergy',
      'Food allergy',
      'Latex allergy',
    ],
    diagnosis_list: [
      'Hypertension',
      'Coronary artery disease',
      'Arrhythmia',
      'Heart failure',
      'Chest pain',
      'High cholesterol',
    ],
    surgery_suggested_list: [
      'Angioplasty',
      'Bypass surgery',
      'Pacemaker insertion',
      'Valve replacement',
    ],
    dietary_suggestions_list: [
      'Reduce salt and sodium intake.',
      'Eat heart-healthy fats like olive oil.',
      'Increase fiber with oats and legumes.',
      'Limit red meat and processed foods.',
      'Drink adequate water daily.',
    ],
  },

  'Interventional Cardiologist': {
    header_order: [
      'Vitals',
      'Diagnosis',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'High salt intake',
      'Sedentary lifestyle',
      'Stress',
      'High fat diet',
    ],
    allergy_list: [
      'Drug allergy',
      'Contrast dye allergy',
      'Food allergy',
      'Latex allergy',
    ],
    diagnosis_list: [
      'Hypertension',
      'Coronary artery disease',
      'Arrhythmia',
      'Heart failure',
      'Chest pain',
      'High cholesterol',
    ],
    surgery_suggested_list: [
      'Angioplasty',
      'Bypass surgery',
      'Pacemaker insertion',
      'Valve replacement',
    ],
    dietary_suggestions_list: [
      'Follow a low-sodium, low-fat diet strictly.',
      'Eat small, frequent meals to avoid strain.',
      'Include potassium-rich foods like bananas.',
      'Avoid trans fats and fried items.',
      'Stay hydrated but limit fluids if advised.',
    ],
  },

  Dentist: {
    header_order: [
      'Diagnosis',
      'Surgery Suggested',
      'Advice',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Allergy',
      'Vitals',
      'Pathology Test Name',
      'Dietary Suggestions',
    ],
    habit_list: [
      'Smoking',
      'Poor oral hygiene',
      'High sugar intake',
      'Teeth grinding',
      'Tobacco chewing',
    ],
    allergy_list: [
      'Anesthesia allergy',
      'Drug allergy',
      'Latex allergy',
      'Metal allergy',
    ],
    diagnosis_list: [
      'Cavity',
      'Gum disease',
      'Tooth decay',
      'Sensitivity',
      'Oral infection',
      'Bad breath',
    ],
    surgery_suggested_list: [
      'Tooth extraction',
      'Root canal',
      'Dental implant',
      'Gum surgery',
      'Wisdom tooth removal',
    ],
    dietary_suggestions_list: [
      'Avoid sticky and sugary foods.',
      'Drink fluoridated water.',
      'Eat crunchy fruits and vegetables for cleaning.',
      'Limit acidic drinks like soda.',
      'Include calcium-rich foods for teeth.',
    ],
  },

  Ophthalmologist: {
    header_order: [
      'Diagnosis',
      'Advice',
      'Follow-Up (days)',
      'Visiting Days',
      'Allergy',
      'Vitals',
      'Pathology Test Name',
      'Dietary Suggestions',
      'Habits',
      'Surgery Suggested',
    ],
    habit_list: [
      'Excess screen time',
      'Poor lighting',
      'Lack of eye care',
      'Reading strain',
      'Sleep deprivation',
    ],
    allergy_list: ['Eye drops allergy', 'Dust', 'Pollen', 'Chemical exposure'],
    diagnosis_list: [
      'Myopia',
      'Hyperopia',
      'Cataract',
      'Glaucoma',
      'Dry eyes',
      'Conjunctivitis',
    ],
    surgery_suggested_list: [
      'LASIK',
      'Cataract surgery',
      'Retinal surgery',
      'Corneal transplant',
    ],
    dietary_suggestions_list: [
      'Eat foods rich in vitamin A like carrots.',
      'Include leafy greens for eye health.',
      'Stay hydrated to prevent dry eyes.',
      'Consume omega-3 fatty acids.',
      'Limit screen time and blink regularly.',
    ],
  },

  Andrologist: {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Pathology Test Name',
      'Advice',
      'Habits',
      'Allergy',
      'Dietary Suggestions',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Sedentary lifestyle',
      'Stress',
      'Poor diet',
      'Obesity',
    ],
    allergy_list: ['Drug allergy', 'Food allergy', 'Latex allergy'],
    diagnosis_list: [
      'Male infertility',
      'Low testosterone',
      'Erectile dysfunction',
      'Varicocele',
      'Prostatitis',
      'Hypogonadism',
      'Sperm abnormalities',
    ],
    surgery_suggested_list: [
      'Varicocelectomy',
      'Testicular biopsy',
      'Sperm retrieval',
      'Vasectomy reversal',
      'Penile implant',
    ],
    dietary_suggestions_list: [
      'Eat zinc-rich foods like nuts and seeds.',
      'Include antioxidants from berries.',
      'Reduce processed foods and sugar.',
      'Stay hydrated with water.',
      'Limit alcohol and caffeine intake.',
    ],
  },

  'Cardiothoracic Surgeon': {
    header_order: [
      'Vitals',
      'Diagnosis',
      'Pathology Test Name',
      'Surgery Suggested',
      'Advice',
      'Allergy',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Dietary Suggestions',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Sedentary lifestyle',
      'High fat diet',
      'Stress',
    ],
    allergy_list: ['Drug allergy', 'Latex allergy', 'Contrast dye allergy'],
    diagnosis_list: [
      'Coronary artery disease',
      'Valvular heart disease',
      'Lung cancer',
      'Aortic aneurysm',
      'Congenital heart defects',
      'Mesothelioma',
      'Thoracic tumors',
    ],
    surgery_suggested_list: [
      'Coronary artery bypass',
      'Heart valve replacement',
      'Lung resection',
      'Thoracotomy',
      'Aortic surgery',
      'Heart transplant',
      'Lung transplant',
    ],
    dietary_suggestions_list: [
      'Follow a low-fat, low-cholesterol diet.',
      'Eat small, nutrient-dense meals.',
      'Avoid smoking and alcohol completely.',
      'Stay hydrated within medical limits.',
      'Include lean proteins for recovery.',
    ],
  },

  'Chest Specialist': {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Habits',
      'Dietary Suggestions',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Passive smoking',
      'Pollution exposure',
      'Sedentary lifestyle',
      'Poor breathing',
    ],
    allergy_list: ['Dust', 'Pollen', 'Smoke', 'Pet dander', 'Mold'],
    diagnosis_list: [
      'Asthma',
      'COPD',
      'Pneumonia',
      'Bronchitis',
      'Pleural effusion',
      'Tuberculosis',
      'Interstitial lung disease',
    ],
    surgery_suggested_list: [
      'Bronchoscopy',
      'Thoracentesis',
      'Lung biopsy',
      'Chest tube insertion',
    ],
    dietary_suggestions_list: [
      'Drink warm fluids to loosen mucus.',
      'Avoid cold and refrigerated items.',
      'Eat antioxidant-rich fruits like oranges.',
      'Include ginger and turmeric for inflammation.',
      'Stay hydrated with boiled water.',
    ],
  },

  Cosmetologist: {
    header_order: [
      'Diagnosis',
      'Advice',
      'Habits',
      'Dietary Suggestions',
      'Allergy',
      'Surgery Suggested',
      'Follow-Up (days)',
      'Visiting Days',
      'Vitals',
      'Pathology Test Name',
    ],
    habit_list: [
      'Sun exposure',
      'Smoking',
      'Poor skincare',
      'Stress',
      'Unhealthy diet',
      'Lack of sleep',
    ],
    allergy_list: [
      'Cosmetics',
      'Fragrance',
      'Parabens',
      'Sulfates',
      'Essential oils',
    ],
    diagnosis_list: [
      'Aging skin',
      'Acne scars',
      'Hyperpigmentation',
      'Wrinkles',
      'Uneven skin tone',
      'Hair thinning',
      'Unwanted hair',
    ],
    surgery_suggested_list: [
      'Botox',
      'Fillers',
      'Chemical peel',
      'Laser resurfacing',
      'Microdermabrasion',
      'Hair transplant',
      'Liposuction',
    ],
    dietary_suggestions_list: [
      'Drink water for skin elasticity.',
      'Eat collagen-boosting foods like berries.',
      'Avoid high-sugar and processed foods.',
      'Include healthy fats for glow.',
      'Limit caffeine and alcohol.',
    ],
  },

  Diabetologist: {
    header_order: [
      'Vitals',
      'Diagnosis',
      'Pathology Test Name',
      'Dietary Suggestions',
      'Advice',
      'Habits',
      'Allergy',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'High sugar intake',
      'Sedentary lifestyle',
      'Smoking',
      'Alcohol',
      'Poor diet',
      'Stress',
    ],
    allergy_list: ['Drug allergy', 'Food allergy', 'Latex allergy'],
    diagnosis_list: [
      'Type 1 diabetes',
      'Type 2 diabetes',
      'Gestational diabetes',
      'Prediabetes',
      'Diabetic neuropathy',
      'Diabetic retinopathy',
      'Diabetic foot',
    ],
    surgery_suggested_list: [
      'Diabetic foot ulcer debridement',
      'Amputation',
      'Bariatric surgery referral',
    ],
    dietary_suggestions_list: [
      'Follow a low-glycemic index diet.',
      'Limit all forms of added sugar.',
      'Eat high-fiber vegetables and whole grains.',
      'Monitor carbohydrate intake strictly.',
      'Stay hydrated with water only.',
    ],
  },

  'Family Medicine': {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Sedentary lifestyle',
      'Poor diet',
      'Stress',
      'Irregular sleep',
    ],
    allergy_list: [
      'Dust',
      'Pollen',
      'Food allergy',
      'Drug allergy',
      'Pet dander',
      'Insect bites',
    ],
    diagnosis_list: [
      'Hypertension',
      'Diabetes',
      'Common cold',
      'Flu',
      'UTI',
      'Gastritis',
      'Anxiety',
      'Depression',
      'Allergies',
      'Arthritis',
    ],
    surgery_suggested_list: [
      'Minor surgery',
      'Skin biopsy',
      'Wound care',
      'Joint injection',
    ],
    dietary_suggestions_list: [
      'Eat a balanced diet with all food groups.',
      'Drink boiled water daily.',
      'Limit processed and fast foods.',
      'Include seasonal fruits and vegetables.',
      'Reduce salt and sugar intake.',
    ],
  },

  'Fertility Specialist': {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Pathology Test Name',
      'Advice',
      'Habits',
      'Allergy',
      'Dietary Suggestions',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Stress',
      'Poor diet',
      'Obesity',
      'Excessive exercise',
    ],
    allergy_list: ['Drug allergy', 'Latex allergy', 'Food allergy'],
    diagnosis_list: [
      'Female infertility',
      'Male infertility',
      'PCOS',
      'Endometriosis',
      'Uterine fibroids',
      'Ovulation disorders',
      'Sperm abnormalities',
      'Recurrent pregnancy loss',
    ],
    surgery_suggested_list: [
      'IVF',
      'ICSI',
      'IUI',
      'Laparoscopy',
      'Hysteroscopy',
      'Egg retrieval',
      'Embryo transfer',
    ],
    dietary_suggestions_list: [
      'Eat folate-rich foods like spinach.',
      'Include healthy fats from avocados.',
      'Limit caffeine and alcohol completely.',
      'Stay hydrated with water.',
      'Maintain a healthy BMI with balanced meals.',
    ],
  },

  Gastroenterologist: {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Dietary Suggestions',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Spicy food',
      'Irregular meals',
      'Stress',
      'Sedentary lifestyle',
    ],
    allergy_list: ['Food allergy', 'Drug allergy', 'Latex allergy'],
    diagnosis_list: [
      'Gastritis',
      'GERD',
      'IBS',
      'Ulcerative colitis',
      "Crohn's disease",
      'Hepatitis',
      'Gallstones',
      'Pancreatitis',
    ],
    surgery_suggested_list: [
      'Endoscopy',
      'Colonoscopy',
      'Gallbladder removal',
      'Bowel resection',
    ],
    dietary_suggestions_list: [
      'Avoid spicy, oily, and fried foods.',
      'Eat small, frequent meals.',
      'Stay hydrated with warm water.',
      'Include probiotics like yogurt.',
      'Limit dairy if lactose intolerant.',
    ],
  },

  'General Surgeon': {
    header_order: [
      'Diagnosis',
      'Surgery Suggested',
      'Vitals',
      'Pathology Test Name',
      'Advice',
      'Allergy',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Dietary Suggestions',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Sedentary lifestyle',
      'Poor diet',
      'Obesity',
    ],
    allergy_list: ['Drug allergy', 'Latex allergy', 'Anesthesia allergy'],
    diagnosis_list: [
      'Hernia',
      'Gallstones',
      'Appendicitis',
      'Breast lump',
      'Thyroid nodules',
      'Hemorrhoids',
      'Pilonidal sinus',
    ],
    surgery_suggested_list: [
      'Hernia repair',
      'Cholecystectomy',
      'Appendectomy',
      'Mastectomy',
      'Thyroidectomy',
      'Hemorrhoidectomy',
      'Laparoscopic surgery',
    ],
    dietary_suggestions_list: [
      'Start with clear liquids after surgery.',
      'Eat soft, easily digestible foods.',
      'Increase protein for wound healing.',
      'Stay hydrated with boiled water.',
      'Avoid gas-forming foods like beans.',
    ],
  },

  Neurologist: {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Advice',
      'Pathology Test Name',
      'Habits',
      'Allergy',
      'Dietary Suggestions',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Poor sleep',
      'Stress',
      'Sedentary lifestyle',
    ],
    allergy_list: ['Drug allergy', 'Food allergy', 'Latex allergy'],
    diagnosis_list: [
      'Migraine',
      'Epilepsy',
      'Stroke',
      "Parkinson's disease",
      'Multiple sclerosis',
      "Alzheimer's",
      'Neuropathy',
      'Headache',
    ],
    surgery_suggested_list: [
      'Brain surgery referral',
      'Spine surgery referral',
      'Deep brain stimulation',
    ],
    dietary_suggestions_list: [
      'Eat magnesium-rich foods for migraines.',
      'Avoid artificial sweeteners and MSG.',
      'Stay hydrated to prevent headaches.',
      'Include omega-3 fatty acids.',
      'Limit caffeine and alcohol.',
    ],
  },

  'Plastic Surgeon': {
    header_order: [
      'Diagnosis',
      'Surgery Suggested',
      'Advice',
      'Habits',
      'Allergy',
      'Follow-Up (days)',
      'Visiting Days',
      'Vitals',
      'Pathology Test Name',
      'Dietary Suggestions',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Sun exposure',
      'Poor nutrition',
      'Stress',
    ],
    allergy_list: [
      'Drug allergy',
      'Latex allergy',
      'Anesthesia allergy',
      'Metal allergy',
    ],
    diagnosis_list: [
      'Burn scars',
      'Traumatic injuries',
      'Birth defects',
      'Breast asymmetry',
      'Rhinoplasty concerns',
      'Aging concerns',
      'Post-weight loss excess skin',
    ],
    surgery_suggested_list: [
      'Rhinoplasty',
      'Breast augmentation',
      'Liposuction',
      'Facelift',
      'Blepharoplasty',
      'Abdominoplasty',
      'Burn reconstruction',
      'Cleft lip repair',
    ],
    dietary_suggestions_list: [
      'Eat high-protein foods for healing.',
      'Stay hydrated with water.',
      'Avoid smoking and alcohol for recovery.',
      'Include vitamin C-rich foods.',
      'Limit sodium to reduce swelling.',
    ],
  },

  Pulmonologist: {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Allergy',
      'Pathology Test Name',
      'Advice',
      'Habits',
      'Dietary Suggestions',
      'Follow-Up (days)',
      'Visiting Days',
      'Surgery Suggested',
    ],
    habit_list: [
      'Smoking',
      'Passive smoking',
      'Pollution exposure',
      'Sedentary lifestyle',
      'Poor breathing',
    ],
    allergy_list: [
      'Dust',
      'Pollen',
      'Smoke',
      'Pet dander',
      'Mold',
      'Chemicals',
    ],
    diagnosis_list: [
      'Asthma',
      'COPD',
      'Pneumonia',
      'Pulmonary fibrosis',
      'Lung cancer',
      'Sleep apnea',
      'Bronchiectasis',
      'Tuberculosis',
    ],
    surgery_suggested_list: [
      'Bronchoscopy',
      'Lung biopsy',
      'Thoracentesis',
      'Pulmonary rehabilitation',
    ],
    dietary_suggestions_list: [
      'Drink warm fluids to ease breathing.',
      'Avoid cold and mucus-forming foods.',
      'Eat antioxidant-rich fruits.',
      'Stay hydrated with boiled water.',
      'Limit dairy if it increases phlegm.',
    ],
  },

  Psychologist: {
    header_order: [
      'Diagnosis',
      'Advice',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Allergy',
      'Vitals',
      'Dietary Suggestions',
      'Pathology Test Name',
      'Surgery Suggested',
    ],
    habit_list: [
      'Stress',
      'Poor sleep',
      'Social isolation',
      'Lack of exercise',
      'Unhealthy coping',
      'Negative thinking patterns',
    ],
    allergy_list: ['Drug allergy', 'Food allergy'],
    diagnosis_list: [
      'Anxiety disorders',
      'Depression',
      'Phobias',
      'PTSD',
      'OCD',
      'Eating disorders',
      'Relationship issues',
      'Stress management',
      'Adjustment disorder',
    ],
    surgery_suggested_list: [],
    dietary_suggestions_list: [
      'Eat regular meals to stabilize mood.',
      'Include omega-3s for brain health.',
      'Limit caffeine and sugar to reduce anxiety.',
      'Stay hydrated with water.',
      'Avoid skipping meals.',
    ],
  },

  Urologist: {
    header_order: [
      'Diagnosis',
      'Vitals',
      'Pathology Test Name',
      'Surgery Suggested',
      'Advice',
      'Habits',
      'Allergy',
      'Dietary Suggestions',
      'Follow-Up (days)',
      'Visiting Days',
    ],
    habit_list: [
      'Smoking',
      'Alcohol',
      'Sedentary lifestyle',
      'Poor hydration',
      'Frequent holding of urine',
    ],
    allergy_list: ['Drug allergy', 'Latex allergy', 'Food allergy'],
    diagnosis_list: [
      'UTI',
      'Kidney stones',
      'BPH',
      'Prostate cancer',
      'Bladder cancer',
      'Incontinence',
      'Erectile dysfunction',
      'Male infertility',
    ],
    surgery_suggested_list: [
      'TURP',
      'Lithotripsy',
      'Prostatectomy',
      'Nephrectomy',
      'Cystoscopy',
      'Vasectomy',
      'Urethroplasty',
    ],
    dietary_suggestions_list: [
      'Drink plenty of water daily.',
      'Reduce salt and oxalate-rich foods.',
      'Limit caffeine and alcohol.',
      'Include citrus fruits for stone prevention.',
      'Avoid spicy and acidic foods for UTI.',
    ],
  },

  Psychiatrist: {
    header_order: [
      'Diagnosis',
      'Advice',
      'Habits',
      'Follow-Up (days)',
      'Visiting Days',
      'Allergy',
      'Vitals',
      'Dietary Suggestions',
      'Pathology Test Name',
      'Surgery Suggested',
    ],
    habit_list: [
      'Alcohol',
      'Smoking',
      'Poor sleep',
      'Stress',
      'Drug abuse',
      'Social isolation',
    ],
    allergy_list: [
      'Drug allergy',
      'Food allergy',
      'Environmental allergy',
      'Latex allergy',
    ],
    diagnosis_list: [
      'Depression',
      'Anxiety',
      'Stress disorder',
      'Bipolar disorder',
      'Insomnia',
      'Panic disorder',
    ],
    surgery_suggested_list: ['Electroconvulsive therapy (ECT)'],
    dietary_suggestions_list: [
      'Eat nutrient-dense meals regularly.',
      'Include complex carbohydrates for serotonin.',
      'Limit caffeine and alcohol.',
      'Stay hydrated with water.',
      'Avoid processed foods and excess sugar.',
    ],
  },
} as const;

export type DoctorSpecialty = keyof typeof DOCTOR_SPECIALTY_CONFIG;

// Type guard to check if a string is a valid specialty
export function isValidSpecialty(
  specialty: string
): specialty is DoctorSpecialty {
  return specialty in DOCTOR_SPECIALTY_CONFIG;
}
